apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-fe
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: api
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: simple-fe/rolling
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated: 
      prune: {{ .Values.spec.syncPolicy.automated.prune }} 
      selfHeal:  {{ .Values.spec.syncPolicy.automated.selfHeal }} 
