

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-fe-deploy
  namespace: fe    
  
  labels:
    app: simple-fe
    
   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-fe
  template:
    metadata:
      labels:
        app: simple-fe     
      

    spec:
      containers:
        - name: simple-fe
          image: saturn203/simple-fe
          ports:
          - name: http
            containerPort: 8080
  
