spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/io203/simple-gitOps.git
    targetRevision: master
  syncPolicy:
    automated: 
      prune: false 
      selfHeal: false  