apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- simple-api-rollout.yaml
- simple-api-svc-active.yaml
- simple-api-svc-preview.yaml
- simple-api-ingress-preview.yaml
- simple-api-ingress.yaml

images:
- name: saturn203/simple-api
  newTag: jenkins-RB0.0.3
